# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.
os: linux

language: node_js

node_js:
  - 12

cache:
  - npm
  - pip

script:
  - sudo apt update
  - sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
  - python3 -m pip install pipenv

  - mkdir -p tmp
  - cd tmp
  -   rsync -avzh ../travis-check-leak/ .
  -   pipenv sync
  -   pipenv run python3 main.py
  -   pipenv run python3 main.py $TRAVIS_BUILD_DIR
  - cd ..

import:
  - credentials.yml