
# https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
# https://docs.travis-ci.com/user/conditions-v1
stages:

# docker_build_stages_start

  - name: installPycharm
# docker_build_stages_end

  - name: Build_docker
  - name: Unit_test
  - name: Merge
  - name: Cron
    if: type = cron
