timeout 60 docker run -t logickee/ubuntu-1804-zsh /installIntellij.sh | tee logs/docker_installIntellij.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installPycharm.sh | tee logs/docker_installPycharm.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installAliWangWang.sh | tee logs/docker_installAliWangWang.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installAndroidStudio.sh | tee logs/docker_installAndroidStudio.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installArgos.sh | tee logs/docker_installArgos.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installCaffeine.sh | tee logs/docker_installCaffeine.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installChinese.sh | tee logs/docker_installChinese.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installCode.sh | tee logs/docker_installCode.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installCUHKUbuntuRepo.sh | tee logs/docker_installCUHKUbuntuRepo.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installDocker.sh | tee logs/docker_installDocker.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installDockerCompose.sh | tee logs/docker_installDockerCompose.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installDynamicTopBar.sh | tee logs/docker_installDynamicTopBar.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installFirebaseTools.sh | tee logs/docker_installFirebaseTools.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installFranz.sh | tee logs/docker_installFranz.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installFreecad.sh | tee logs/docker_installFreecad.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installFresh.sh | tee logs/docker_installFresh.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installGestureDelete.sh | tee logs/docker_installGestureDelete.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installGit.sh | tee logs/docker_installGit.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installGitKraken.sh | tee logs/docker_installGitKraken.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installGnomeAnimations.sh | tee logs/docker_installGnomeAnimations.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installGnomeUtil.sh | tee logs/docker_installGnomeUtil.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installGsconnect.sh | tee logs/docker_installGsconnect.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installHelloworld.sh | tee logs/docker_installHelloworld.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installInkscape.sh | tee logs/docker_installInkscape.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installKicad.sh | tee logs/docker_installKicad.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installKrita.sh | tee logs/docker_installKrita.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installLaCapitaine.sh | tee logs/docker_installLaCapitaine.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installLibreoffice.sh | tee logs/docker_installLibreoffice.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installMagicWormHole.sh | tee logs/docker_installMagicWormHole.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installMeld.sh | tee logs/docker_installMeld.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installNautilus.sh | tee logs/docker_installNautilus.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installNetworkManager.sh | tee logs/docker_installNetworkManager.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installNgrok.sh | tee logs/docker_installNgrok.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installNode.sh | tee logs/docker_installNode.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installNoMachine.sh | tee logs/docker_installNoMachine.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installObsStudio.sh | tee logs/docker_installObsStudio.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installOhMyTmux.sh | tee logs/docker_installOhMyTmux.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installOpenSCAD.sh | tee logs/docker_installOpenSCAD.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installOpenWeather.sh | tee logs/docker_installOpenWeather.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installPaperIcon.sh | tee logs/docker_installPaperIcon.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installPowerLineFonts.sh | tee logs/docker_installPowerLineFonts.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installPython.sh | tee logs/docker_installPython.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installRclone.sh | tee logs/docker_installRclone.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installScreenSaver.sh | tee logs/docker_installScreenSaver.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installSpf13.sh | tee logs/docker_installSpf13.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installSsh.sh | tee logs/docker_installSsh.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installStacer.sh | tee logs/docker_installStacer.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installSynergy.sh | tee logs/docker_installSynergy.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installTilix.sh | tee logs/docker_installTilix.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installTmate.sh | tee logs/docker_installTmate.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installTmateWrapper.sh | tee logs/docker_installTmateWrapper.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installTmux.sh | tee logs/docker_installTmux.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installXnView.sh | tee logs/docker_installXnView.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installYarn.sh | tee logs/docker_installYarn.log
timeout 60 docker run -t logickee/ubuntu-1804-zsh /installZsh.sh | tee logs/docker_installZsh.log