#!/usr/bin/env python3

import os,sys
from pprint import pprint
import shlex
from subprocess import check_output
import re

syncWorkDir_template='''  syncWorkDir "/home/logic/_workspace/{{playlistName}}" &'''.rstrip()

master_template='''  # gen_syncWorkDir_start
  # generated by scripts/gen_syncWorkDir.py, don't edit this directly !!!

{{syncWorkDirCommands}}

  # gen_syncWorkDir_end
'''.rstrip()

def genPlaylist(playlist_dirname):
  return syncWorkDir_template.replace('{{playlistName}}',playlist_dirname)

def genMasterPlaylist(syncPlayListCommands):
  return master_template.replace('{{syncWorkDirCommands}}',syncPlayListCommands)

def get_sub_folders(path):
    all_sub_directories_list = os.popen("find {}/*playlist -type d -maxdepth 0".format(path)).read().splitlines()
    return all_sub_directories_list

def updateDotLouisAlias(syncString):
  # f_in = open('/home/logic/_workspace/dotfiles/.louis_alias','r+')
  f_in = open('/home/logic/_workspace/dotfiles/.louis_alias','r+')

  dotfile_content = ''.join(f_in.readlines())
  dotfile_content=re.sub("  # gen_syncWorkDir_start.*  # gen_syncWorkDir_end", syncString,dotfile_content,flags=re.IGNORECASE|re.MULTILINE|re.DOTALL)

  print(dotfile_content)
  f_in.seek(0)
  f_in.truncate()
  f_in.writelines([dotfile_content])
  f_in.close()


def main():
  test_dirs = get_sub_folders('/home/logic/_workspace')
  playlist_names = map(lambda x: x.split('/')[-1], test_dirs)

  return updateDotLouisAlias(
    genMasterPlaylist(
      '\n'.join(genPlaylist(playlist_name) for playlist_name in playlist_names)
    )
  )



if __name__ =='__main__':
  print(main())